services:
  fastapizero_database:
    image: postgres:latest
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  fastapizero_app:
    image: fastapi_zero:latest
    build: .
    entrypoint: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - fastapizero_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@fastapizero_database:5432/app_db
      
volumes:
  pgdata: